on:
  push:
    branches: [develop]

jobs:
  create-pr-from-develop:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: check-if-pr-exists
        id: check_pr_exists
        run: |
          prs=$(gh pr list \
          --repo ${{ github.repository }} \
          --head 'develop' \
          --base 'main' \
          --json title \
          --jq 'length')
          if ((prs > 0)); then
          echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      - name: create-pr
        if: !steps.check_pr_exists.outputs.skip
        run: |
          gh pr --repo ${{ github.repository }} \
          create --base main --head develop \
          --title "Sync develop to main" \
          --body "Sync develop to main"
