on:
  push:
    branches: [develop]

jobs:
  create-pr-from-develop:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: create-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr --repo ${{ github.repository }} \
          create --base main --head develop \
          --fill
